Use errorprone plugin's built-in configuration
Apply baseline-error-prone plugin using the errorprone configuration.

Resolve compilation problems when applying this plugin and working in Eclipse due to Eclipse classpath mangling with the processors plugin, which correctly applies the configuration's classpath to Eclipse's single classpath and where this plugin should not appear on the actual compilation classpath.

In particular, when using other processor plugins, this change will correct errors such as:
    Errors running builder 'Java Builder' on project 'glyph'.
        java.lang.ClassCastException: org.immutables.value.internal.$processor$.$Processor cannot be cast to javax.annotation.processing.Processor