Bump error-prone to 2.40.0 (#3165)
Upgrade error-prone to 2.40.0 and stop errors of the form when error-prone >2.39.0 is used:

```
java.lang.NoSuchMethodError: 'java.util.Optional com.google.errorprone.util.ASTHelpers.findSuperMethod(com.sun.tools.javac.code.Symbol$MethodSymbol, com.sun.tools.javac.code.Types)'
        at com.palantir.baseline.errorprone.ThrowSpecificity.matchMethod(ThrowSpecificity.java:68)
```