[feature] New `com.palantir.baseline-release-compatibility` plugin (#582)
<!-- PR title should start with '[fix]', '[improvement]' or '[break]' if this PR would cause a patch, minor or major SemVer bump. Omit the prefix if this PR doesn't warrant a standalone release. -->

## Before this PR
<!-- Describe the problem you encountered with the current state of the world (or link to an issue) and why it's important to fix now. -->
When compiling with `targetCompatibility = 1.8` while running on JDK 9+, one may accidentally introduce binary incompatibilities in the generated byte code as it is implicitly linked against the building JDK's class files. This can lead to runtime issues, for example running on JDK 8 `java.lang.NoSuchMethodError: java.nio.ByteBuffer.rewind()Ljava/nio/ByteBuffer;` as seen in https://github.com/palantir/conjure-java/pull/293

## After this PR
<!-- Describe at a high-level why this approach is better. -->
When using JDK 9+ to compile with a `targetCompatibility` less than JDK 9, this plugin adds compiler arguments per [JEP 247](https://openjdk.java.net/jeps/247) to explicitly set the target JDK platform API to maintain binary compatibility.

See also [Gradle JDK release issue](https://github.com/gradle/gradle/issues/2510).

<!-- Reference any existing GitHub issues, e.g. 'fixes #000' or 'relevant to #000' -->